update camelvertx

diff --git a/openshift-origin-cartridge-camelvertx/bin/control_vertx b/openshift-origin-cartridge-camelvertx/bin/control_vertx
--- a/openshift-origin-cartridge-camelvertx/bin/control_vertx
+++ b/openshift-origin-cartridge-camelvertx/bin/control_vertx
@@ -7,17 +7,88 @@ camelvertx_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/camelvertx.pid
 
 cartridge_type="camelvertx"
 
+CAMELVERTX_BIN_DIR=${OPENSHIFT_CAMELVERTX_DIR}/bin
+CAMELVERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/camelvertx.pid
+
+# Check if the jbossas process is running
+function isrunning() {
+    
+    # Check for running app
+    if [ -f "$CAMELVERTX_PID_FILE" ]; then
+      jbpid=$(cat $CAMELVERTX_PID_FILE);
+      if /bin/ps --pid $jbpid 1>&2 >/dev/null;
+      then
+        return 0
+      fi
+    fi
+   
+    return 1
+}
+
+# Kill the process given by $1 and its children
+killtree() {
+    local _pid=$1
+    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
+        killtree ${_child}
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ -z $should_be_gone_pid ]; then
+        return
+    else
+        kill -TERM ${_pid}
+    fi
+
+    local count=0
+    while [ ${count} -lt 15 ]
+    do
+        local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+        if [ -z $should_be_gone_pid ]; then
+                return
+        else
+                sleep 2
+                let count=${count}+1
+        fi
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ ! -z $should_be_gone_pid ]
+    then
+        kill -9 ${_pid}
+    fi
+}
+
+function stop() {
+  echo "Stopping $cartridge_type cart"
+  
+  if isrunning; then
+		if [ -f "$CAMELVERTX_PID_FILE" ]; then
+      pid=$(cat $CAMELVERTX_PID_FILE);
+      echo "Sending SIGTERM to jboss:$pid ..." 1>&2
+      killtree $pid
+    else 
+	    echo "Failed to locate JBOSS PID File" 1>&2
+	  fi
+  fi
+}
+
 function build() {
     
     	pushd ${OPENSHIFT_REPO_DIR} > /dev/null
     	
-    	OPENSHIFT_CAMELVERTX_CLUSTER="${OPENSHIFT_CAMELVERTX_IP}"
+    	if [ -z $OPENSHIFT_CAMELVERTX_CLUSTER ]; then
+    		OPENSHIFT_CAMELVERTX_CLUSTER="${OPENSHIFT_CAMELVERTX_IP}"
+    	fi
+    	
+    	cp ${OPENSHIFT_REPO_DIR}/vert.x-1.3.1.final/conf/cluster.xml $OPENSHIFT_CAMELVERTX_DIR/template/vert.x-1.3.1.final/conf/
+    	
+    	OPENSHIFT_CAMELVERTX_PROXY_IP=$(nslookup ${OPENSHIFT_GEAR_DNS} | awk '/^Address: / { print $2 ; exit }')
     	
     	pushd $OPENSHIFT_CAMELVERTX_DIR/template
-  			sed -i -e "s/\${env.OPENSHIFT_CAMELVERTX_IP}/${OPENSHIFT_CAMELVERTX_IP}/g" \
+  			sed -i -e "s/\${env.OPENSHIFT_CAMELVERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_CAMELVERTX_CLUSTER_PROXY_PORT}/g" \
+  					-e "s/\${env.OPENSHIFT_CAMELVERTX_PROXY_IP}/${OPENSHIFT_CAMELVERTX_PROXY_IP}/g" \
   					-e "s/\${env.OPENSHIFT_CAMELVERTX_CLUSTER}/${OPENSHIFT_CAMELVERTX_CLUSTER}/g" \
   					./vert.x-1.3.1.final/conf/cluster.xml
-  			sed -i -e "s/\${env.OPENSHIFT_CAMELVERTX_IP}/${OPENSHIFT_CAMELVERTX_IP}/g" ./bin/run-vertx.sh
 		popd
 
 }
@@ -39,12 +110,24 @@ function start() {
 
 	pushd ${OPENSHIFT_CAMELVERTX_DIR}/template
 		./bin/run-vertx.sh &
+		PROCESS_ID=$!
+    	echo "$PROCESS_ID" > ${CAMELVERTX_PID_FILE}
 	popd
 
 }
 
+function restart() {
+    echo "Restarting $cartridge_type cart"
+   
+  	stop
+  	
+  	start
+}
+
 case "$1" in
   start)        start ;;
+  stop)			stop ;;
+  restart) 		restart ;;
   *)            exit 0
 esac
 
